name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        scala: [3.3.0]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          check-latest: true

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Check formatting
        run: sbt fixCheck
      - name: Compile and test
        run: sbt test

      - name: Publish artifacts
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: sbt ++${{ matrix.scala }} ci-release

  ci-passed:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ':'
